import os

nome = input("Nome:")
CPF = input("CPF:")
RG = input("RG:")
Nascimento = input("Data de nascimento:")
Sexo = input("Seu sexo:")
Peso = input("Seu peso:")
Sangue = input("Tipo sanguineo")
Renda = input("Renda:")
Endereço = input("Seu endereço:")
Telefone = input("Seu telefone: ")
Cidade = input("Sua cidade:")
Estado = input("Seu estado:")
os.system('cls')



print("Nome:", nome)
print("CPF:",CPF)
print("RG:",RG)
print("Data de nascimento:", Nascimento)
print("Seu sexo:",Sexo)
print("Seu peso:",Peso)
print("Tipo sanguineo:",Sangue)
print("Renda:",Renda)
print("Seu endereço:",Endereço)
print("Seu telefone:",Telefone)
print("Sua cidade:", Cidade)
print("Seu estado:",Estado)